import os
from pathlib import Path
from PIL import Image

# Paths
NPC_SHEETS_DIR = Path("images/characters/map/sheets/npc")

TARGETS = [
    "holographic_log_orb_sheet.png",
    "ancient_tide_bell_sheet.png",
    "toll_bridge_marker_sheet.png",
    "bone_shard_sheet.png",
    "silver_locket_sheet.png",
    "squad_insignia_sheet.png",
    "cursed_idol_sheet.png"
]

TARGET_WIDTH = 1024
WEBP_QUALITY = 85

def process_npc_sprite(filename):
    file_path = NPC_SHEETS_DIR / filename
    if not file_path.exists():
        print(f"Skipping {filename}: File not found.")
        return

    print(f"Processing {filename}...")
    try:
        with Image.open(file_path) as img:
            img = img.convert("RGBA")
            datas = img.getdata()

            new_data = []
            for item in datas:
                # Remove clean white background generated by Gemini synthesis
                if item[0] > 240 and item[1] > 240 and item[2] > 240:
                    new_data.append((255, 255, 255, 0))
                else:
                    new_data.append(item)

            # Update image buffer with transparent alpha channel
            img.putdata(new_data)
            
            # Save original transparent PNG back to satisfy mapped npcs.js references
            img.save(file_path, "PNG")
            print(f"  * Transparent background applied successfully to {filename}")

            # Create optimized _low.webp asset buffer
            w, h = img.size
            if w > TARGET_WIDTH:
                ratio = TARGET_WIDTH / float(w)
                new_w = TARGET_WIDTH
                new_h = int(float(h) * ratio)
                img_low = img.resize((new_w, new_h), Image.Resampling.LANCZOS)
            else:
                img_low = img

            low_webp_filename = filename.replace(".png", "_low.webp")
            low_webp_path = NPC_SHEETS_DIR / low_webp_filename
            img_low.save(low_webp_path, "WEBP", quality=WEBP_QUALITY)
            print(f"  * Optimized low-weight WebP saved successfully as {low_webp_filename}")

    except Exception as e:
        print(f"  * FAILED processing {filename}: {e}")

if __name__ == "__main__":
    print("RPG+ Local Item Background Removal & WebP Transcoder")
    print("====================================================")
    for target in TARGETS:
        process_npc_sprite(target)
    print("\nBatch processing fully completed.")
